name: TheEnchanting
description: The Enchanting Plugin
main: com.qualityplus.enchanting.TheEnchanting
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
softdepend: [EcoEnchants]
commands:
  theenchanting:
    aliases: ["enchanting", "theench"]
    description: Enchanting's main command