name: TheDragon
description: The Dragon Plugin
main: com.qualityplus.dragon.TheDragon
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
commands:
  thedragon:
    aliases: ["dragon", "drg"]
    description: TheDragon's main command