name: TheAuction
description: The Auction Plugin
main: com.qualityplus.auction.TheAuction
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
commands:
  theauction:
    aliases: [ah, auctionhouse, auction]
    description: TheAuction's main command