name: TheAssistant
description: The Assistant Plugin
main: com.qualityplus.assistant.TheAssistantPlugin
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
loadbefore: [SkinsRestorer, ajLeaderboards]
softdepend: [MythicMobs, Vault, TokenManager, PlayerPoints, WorldEdit, WorldGuard, UltraRegions, Residence, ProtocolLib, PlaceholderAPI, MVdWPlaceholderAPI]
