name: TheTrades
description: The Trades Plugin
main: com.qualityplus.trades.TheTrades
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
commands:
  thetrades:
    aliases: ["trades"]
    description: Trades's main command