name: ThePets
description: The Pets Plugin
main: com.qualityplus.pets.ThePets
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
commands:
  pets:
    aliases: ["pet", "p"]
    description: Pets's main command