name: TheAlchemist
description: The Alchemist Plugin
main: com.qualityplus.alchemist.TheAlchemist
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
commands:
  thealchemist:
    aliases: ["alchemist", "alch"]
    description: Alchemist's main command