name: TheCrafting
description: The Crafting Plugin
main: com.qualityplus.crafting.TheCrafting
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
commands:
  thecrafting:
    aliases: ["crafting", "tc"]
    description: Crafting's main command